type Languages {
  value: String!
  label: String!
}

input LanguagesInput {
  value: String!
  label: String!
}

type User {
  _id: ID!
  name: String!
  celphone: String!
  cpf: String!
  cep: String!
  neighborhood: String!
  street: String!
  city: String!
  email: String!
  password: String!
  languages: [Languages]!
}

input UserInput {
  name: String!
  celphone: String!
  cpf: String!
  cep: String!
  neighborhood: String!
  street: String!
  city: String!
  email: String!
  password: String!
  languages: [LanguagesInput]!
}

type Query {
  users: [User!]!
  user(id: ID!): User!
}

type Mutation {
  createUser(data: UserInput): User!
  updateUser(id: ID!, data: UserInput!): User!
  deleteUser(id: ID!): Boolean
}
